spring:
  datasource:
    url : jdbc:mysql://localhost:3306/fabricVendor?useSSL=False
    username : // Enter the user name of the DB
    password : // Enter the password of the DB

#JPA settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true